version: '3.3'

services:

    snibox:
        image: melashri/snibox    
        container_name: snibox
        volumes:
            - ./app/db:/app/db/database
        ports:
            - "8200:3000"
        restart: unless-stopped

        
